### ISSUE TITLE
Allow Customizing Translation Location

### ISSUE THREAD

**Issue by Crisfole** [apsislabs/phi_attrs#36]
Translations are currently hard coded into the translation namespace `phi`:

```yaml
en:
  phi:
    controller:
      action:
        model: "Whatever"
```

We could easily allow that to be customized like the log location.
